services:
  portrait-api:
    build:
      context: .
      dockerfile: ./app/DockerFile
    ports:
      - "8000:8000"
    container_name: portrait-api
    # network_mode: "host"
    networks:
      - app-network
    env_file:
      - .env
  portrait-mqtt-tasker:
    build:
      context: .
      dockerfile: ./tasker/DockerFile
    container_name: portrait-mqtt-tasker
    env_file:
      - .env
    # restart: always

networks:
  app-network:
    driver: bridge