services:
  portrait-api:
    build:
      context: .
      dockerfile: ./app/DockerFile
    image: wesleygas/portrait-api
    ports:
      - "5718:8000"
    container_name: portrait-api
    networks:
      - app-network
    env_file:
      - .env
  portrait-mqtt-tasker:
    build:
      context: .
      dockerfile: ./tasker/DockerFile
    image: wesleygas/portrait-mqtt-tasker
    container_name: portrait-mqtt-tasker
    env_file:
      - .env

networks:
  app-network:
    driver: bridge